/** Wikipedia links for notable list participants */
export const WIKIPEDIA_LINKS: Record<string, string> = {
  'Eliezer Yudkowsky': 'https://en.wikipedia.org/wiki/Eliezer_Yudkowsky',
  'Robin Hanson': 'https://en.wikipedia.org/wiki/Robin_Hanson',
  'Hal Finney': 'https://en.wikipedia.org/wiki/Hal_Finney_(computer_scientist)',
  'Nick Bostrom': 'https://en.wikipedia.org/wiki/Nick_Bostrom',
  'Max More': 'https://en.wikipedia.org/wiki/Max_More',
  'Anders Sandberg': 'https://en.wikipedia.org/wiki/Anders_Sandberg',
  'Damien Broderick': 'https://en.wikipedia.org/wiki/Damien_Broderick',
  'Lee Daniel Crocker': 'https://en.wikipedia.org/wiki/Lee_Daniel_Crocker',
  'Amara Graps': 'https://en.wikipedia.org/wiki/Amara_Graps',
  'Nick Szabo': 'https://en.wikipedia.org/wiki/Nick_Szabo',
  'Wei Dai': 'https://en.wikipedia.org/wiki/Wei_Dai',
  'David Friedman': 'https://en.wikipedia.org/wiki/David_D._Friedman',
  'Natasha Vita-More': 'https://en.wikipedia.org/wiki/Natasha_Vita-More',
  'Ralph Merkle': 'https://en.wikipedia.org/wiki/Ralph_Merkle',
  'Eric Drexler': 'https://en.wikipedia.org/wiki/K._Eric_Drexler',
  'Hans Moravec': 'https://en.wikipedia.org/wiki/Hans_Moravec',
  'Gregory Benford': 'https://en.wikipedia.org/wiki/Gregory_Benford',
  'Vernor Vinge': 'https://en.wikipedia.org/wiki/Vernor_Vinge',
  'Alexander Chislenko': 'https://en.wikipedia.org/wiki/Alexander_Chislenko',
  'Perry Metzger': 'https://en.wikipedia.org/wiki/Perry_E._Metzger',
  'Curt Adams': 'https://en.wikipedia.org/wiki/Curt_Adams',
  'Julian Assange': 'https://en.wikipedia.org/wiki/Julian_Assange',
}
